site_name: YH Specs 2.0
site_description: Updated on  2025-11-24

theme:
  name: material

features:
  # Top-level items become tabs in the header
  - navigation.tabs
  # Shows the tab for the current section in the sidebar
  - navigation.sections
  # Fixes the sidebar, keeping it visible as the user scrolls
  - navigation.sticky
  # Shows the table of contents in the sidebar as the user scrolls
  - toc.follow
  # Makes the table of contents on the right sticky
  - toc.sticky
  # Search suggestions and results highlighting
  - search.suggest
  - search.highlight
  # Gives the documentation a cleaner, more readable font
  - typography
nav:
  - Home: index.md
  - Pathways: pathways.md
  - Data Structures: structures.md
  - Enums: enums.md
  - Glossary: glossary.md

markdown_extensions:
  - admonition # Used for callouts/notes
  - def_list # Definition lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences: # Used for Mermaid and code annotations
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details # Collapsible sections
  - toc:
      permalink: true
  - tables
  - attr_list

plugins:
  - search
  - macros
  - table-reader
